/** Small same-origin control console. The official DSH Web remains the chat
 * surface inside each Host; this page manages the tenant control-plane data. */
export const CONTROL_PANEL_HTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DSH Tenant Control</title><style>
body{font:14px system-ui,sans-serif;max-width:1100px;margin:32px auto;padding:0 18px;color:#18212f;background:#f6f8fb}h1{margin-bottom:4px}small{color:#657287}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.card{background:white;border:1px solid #dfe5ed;border-radius:12px;padding:16px;box-shadow:0 2px 8px #14213d0b}label{display:block;margin:8px 0 4px;font-weight:600}input,textarea,button,select{font:inherit;width:100%;box-sizing:border-box;padding:8px;border:1px solid #c8d1dd;border-radius:7px}textarea{min-height:100px;font-family:ui-monospace,monospace}button{background:#2166d1;color:white;border:0;cursor:pointer;margin-top:8px}button.secondary{background:#64748b}.row{display:flex;gap:8px}.row>*{flex:1}pre{white-space:pre-wrap;max-height:360px;overflow:auto;background:#111827;color:#e5edf8;padding:12px;border-radius:8px}.ok{color:#087443}.error{color:#b42318}</style></head>
<body><h1>DSH Tenant Control</h1><small>用户配置、Profile、Sandbox 和 Runtime 注册；真实任务仍由 DSH Host → dsh-multica → Multica Daemon 执行。<a href="/">进入 DeepSeek Chat</a></small>
<div class="card" id="authCard"><label>用户 Token</label><input id="token" type="password"><div class="row"><button id="load">加载当前用户</button><button class="secondary" id="clear">清除</button></div></div><p id="status"></p>
<div class="grid"><section class="card"><h2>Profile</h2><pre id="profile">未加载</pre><label>Profile 更新 JSON</label><textarea id="profilePatch" placeholder='{"expectedVersion":1,"plugins":[{"id":"my-plugin","packageName":"@example/dsh-plugin","version":"1.2.3","enabled":true}]}'></textarea><button id="saveProfile">保存并重启用户 Host</button><button class="secondary" id="rollback">回滚到版本 1</button></section>
<section class="card"><h2>Daemon / Runtime</h2><pre id="daemons">未加载</pre><button class="secondary" id="discover">发现当前 workspace 的在线 Daemon</button><select id="candidate"><option value="">尚未发现</option></select><label>显示名称</label><input id="candidateLabel" placeholder="我的电脑"><label>Daemon 工作区根目录</label><input id="candidateRoot" placeholder="C:\\Users\\me\\project 或 /workspace"><label>执行位置</label><select id="candidateMode"><option value="local">本机</option><option value="external">其他远程机器</option></select><button id="registerCandidate">登记所选 Daemon</button><details><summary>高级：手工登记 JSON</summary><textarea id="daemon" placeholder='{"label":"我的电脑","daemonId":"...","workspaceId":"...","runtimeIds":["..."],"executionMode":"external","workspacesRoot":"/workspace","managed":false,"status":"online"}'></textarea><button id="addDaemon">手工登记</button></details><label>当前 Session</label><select id="session"><option value="">先加载或创建 Session</option></select><button id="newSession">创建 Chat Session</button><select id="runtime"><option>加载 Runtime 后选择</option></select><button id="switchRuntime">切换 Runtime</button></section>
<section class="card"><h2>Skill</h2><label>当前用户 Skills JSON 数组</label><textarea id="skills" placeholder='[{"key":"my-skill","name":"My Skill","version":"1","description":"","content":"...","enabled":true}]'></textarea><button id="saveSkills">保存，下一条 Task 生效</button><h2>Chat</h2><textarea id="prompt" placeholder="输入一条消息"></textarea><button id="send">发送</button></section></div>
<section class="card"><h2>Session 事件</h2><div class="row"><button class="secondary" id="watchEvents">监听当前 Session</button><button class="secondary" id="closeSession">关闭当前 Session（可重新打开）</button></div><pre id="events"></pre></section>
<script>
const $=id=>document.getElementById(id), token=$('token'), status=$('status'); token.value=sessionStorage.getItem('dsh-token')||'';
const headers=()=>token.value?{'Authorization':'Bearer '+token.value,'Content-Type':'application/json'}:{'Content-Type':'application/json'};
async function api(path,init={}){if(token.value)sessionStorage.setItem('dsh-token',token.value);const r=await fetch(path,{...init,headers:{...headers(),...(init.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||('HTTP '+r.status));return body}
function show(msg,err=false){status.textContent=msg;status.className=err?'error':'ok'}
async function refreshSessions(){const data=await api('/v1/sessions');const current=$('session').value;$('session').replaceChildren(...(data.sessions||[]).map(x=>{const o=document.createElement('option');o.value=x.sessionId;o.textContent=x.sessionId+' · '+x.status;return o}));if(current&&[...$('session').options].some(x=>x.value===current))$('session').value=current}
async function load(){try{const p=await api('/v1/profile');$('profile').textContent=JSON.stringify(p,null,2);const d=await api('/v1/daemons');$('daemons').textContent=JSON.stringify(d,null,2);$('skills').value=JSON.stringify(p.skills||[],null,2);const r=await api('/v1/runtimes');$('runtime').replaceChildren(...(r.runtimes||[]).map(x=>{const o=document.createElement('option');o.value=JSON.stringify(x);o.textContent=x.label||x.runtimeId;return o}));await refreshSessions();show('已加载 '+p.userId+' Profile v'+p.version)}catch(e){show(e.message,true)}}
async function discover(){const data=await api('/v1/daemon-candidates');$('candidate').replaceChildren(...(data.candidates||[]).map(x=>{const o=document.createElement('option');o.value=JSON.stringify(x);o.textContent=(x.registered?'[已登记] ':'')+x.label+' · '+x.runtimes.map(r=>r.kind).join('/');return o}));const first=$('candidate').value?JSON.parse($('candidate').value):null;if(first)$('candidateLabel').value=first.label;return data}
async function run(fn){try{await fn();show('操作完成')}catch(e){show(e.message,true)}}
$('load').onclick=()=>run(load);$('clear').onclick=()=>{sessionStorage.removeItem('dsh-token');token.value='';show('已清除')};$('saveProfile').onclick=()=>run(async()=>{const p=await api('/v1/profile',{method:'PATCH',body:$('profilePatch').value});$('profile').textContent=JSON.stringify(p,null,2)});$('rollback').onclick=()=>run(async()=>{const p=await api('/v1/profile/rollback',{method:'POST',body:JSON.stringify({targetVersion:1})});$('profile').textContent=JSON.stringify(p.profile,null,2)});$('discover').onclick=()=>run(discover);$('candidate').onchange=()=>{const c=$('candidate').value?JSON.parse($('candidate').value):null;if(c)$('candidateLabel').value=c.label};$('registerCandidate').onclick=()=>run(async()=>{const c=$('candidate').value?JSON.parse($('candidate').value):null;if(!c)throw Error('先发现并选择 Daemon');if(!$('candidateRoot').value.trim())throw Error('请输入该 Daemon 的工作区根目录');await api('/v1/daemons/discover',{method:'POST',body:JSON.stringify({daemonId:c.daemonId,label:$('candidateLabel').value||c.label,workspacesRoot:$('candidateRoot').value,executionMode:$('candidateMode').value})});await load()});$('addDaemon').onclick=()=>run(async()=>{await api('/v1/daemons',{method:'POST',body:$('daemon').value});await load()});$('saveSkills').onclick=()=>run(async()=>{await api('/v1/skills',{method:'PUT',body:JSON.stringify({skills:JSON.parse($('skills').value)})});});$('newSession').onclick=()=>run(async()=>{const p=await api('/v1/sessions',{method:'POST',body:'{}'});await refreshSessions();$('session').value=p.sessionId||p.id;});$('closeSession').onclick=()=>run(async()=>{const s=$('session').value;if(!s)throw Error('先选择 Session');await api('/v1/sessions/'+encodeURIComponent(s),{method:'DELETE'});await refreshSessions();});$('switchRuntime').onclick=()=>run(async()=>{const s=$('session').value;const r=JSON.parse($('runtime').value);await api('/v1/sessions/'+encodeURIComponent(s)+'/runtime',{method:'POST',body:JSON.stringify({runtime:r.kind,runtimeId:r.runtimeId,daemonId:r.daemonId})})});$('watchEvents').onclick=()=>run(async()=>{const s=$('session').value;if(!s)throw Error('先选择 Session');const response=await fetch('/v1/sessions/'+encodeURIComponent(s)+'/events',{headers:headers()});if(!response.ok)throw Error('事件流 HTTP '+response.status);if(!response.body)throw Error('浏览器不支持事件流');const reader=response.body.getReader(),decoder=new TextDecoder();while(true){const part=await reader.read();if(part.done)break;$('events').textContent+=decoder.decode(part.value,{stream:true})}});$('send').onclick=()=>run(async()=>{const s=$('session').value;if(!s)throw Error('先创建 Session');const r=await api('/v1/sessions/'+encodeURIComponent(s)+'/messages',{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),text:$('prompt').value})});$('events').textContent+='submitted '+JSON.stringify(r)+'\\n'});
(async()=>{try{const health=await fetch('/v1/health').then(r=>r.json());if(health.userId){$('authCard').hidden=true;await load()}}catch(e){show(e.message,true)}})();
</script></body></html>`;
